name: Bug Report
description: Report a bug
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Colnade version
      placeholder: "0.5.0"
    validations:
      required: true
  - type: input
    id: backend
    attributes:
      label: Backend
      placeholder: "polars 1.20, pandas 2.2, etc."
