name: Feature Request
description: Suggest a new feature or enhancement
labels: ["feature", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like Colnade to do?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've tried?
